"""add_privacy_fields_to_photos_and_albums

Revision ID: 21d217c87b44
Revises: 0eff2dc34385
Create Date: 2026-02-14 10:49:37.270055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21d217c87b44'
down_revision: Union[str, Sequence[str], None] = '0eff2dc34385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_albums', sa.Column('is_private', sa.Boolean(), nullable=True))
    op.execute("UPDATE photo_albums SET is_private = FALSE")
    op.alter_column('photo_albums', 'is_private', nullable=False)

    op.add_column('user_photos', sa.Column('is_private', sa.Boolean(), nullable=True))
    op.execute("UPDATE user_photos SET is_private = FALSE")
    op.alter_column('user_photos', 'is_private', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_photos', 'is_private')
    op.drop_column('photo_albums', 'is_private')
    # ### end Alembic commands ###
