"""add user photo albums

Revision ID: 26478491c4ad
Revises: b3925f2783ac
Create Date: 2026-02-13 10:34:27.245284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26478491c4ad'
down_revision: Union[str, Sequence[str], None] = 'b3925f2783ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_photos', sa.Column('album_id', sa.Integer(), nullable=True))
    op.add_column('user_photos', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'user_photos', 'photo_albums', ['album_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_photos', type_='foreignkey')
    op.drop_column('user_photos', 'created_at')
    op.drop_column('user_photos', 'album_id')
    op.drop_table('photo_albums')
    # ### end Alembic commands ###
