"""add_client_id_to_chat_messages

Revision ID: 2abe263415bf
Revises: f33c2f49979b
Create Date: 2026-03-01 15:09:51.991459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2abe263415bf'
down_revision: Union[str, Sequence[str], None] = 'f33c2f49979b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Проверяем наличие колонки перед добавлением (для SQLite/Postgres совместимости в ручном режиме)
    conn = op.get_bind()
    columns = [c['name'] for c in sa.inspect(conn).get_columns('chat_messages')]
    if 'client_id' not in columns:
        with op.batch_alter_table('chat_messages', schema=None) as batch_op:
            batch_op.add_column(sa.Column('client_id', sa.String(), nullable=True))
    
    # Другие изменения
    try:
        with op.batch_alter_table('user_photo_reactions', schema=None) as batch_op:
            batch_op.drop_constraint(None, type_='foreignkey')
            batch_op.drop_constraint(None, type_='foreignkey')
            batch_op.create_foreign_key(None, 'user_photos', ['photo_id'], ['id'], ondelete='CASCADE')
            batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
    except Exception:
        pass

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_photo_reactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_photos', ['photo_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
