"""add_album_comments_and_reactions

Revision ID: 3227063fd916
Revises: ea02fa9ce4b6
Create Date: 2026-03-19 10:55:09.070149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3227063fd916'
down_revision: Union[str, Sequence[str], None] = 'ea02fa9ce4b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    # ### commands auto generated by Alembic - please adjust! ###
    if 'photo_album_comments' not in tables:
        op.create_table('photo_album_comments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('album_id', sa.Integer(), nullable=False),
        sa.Column('comment', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['album_id'], ['photo_albums.id'], name=op.f('fk_photo_album_comments_album_id_photo_albums'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_photo_album_comments_user_id_users'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_photo_album_comments'))
        )
    
    if 'photo_album_reactions' not in tables:
        op.create_table('photo_album_reactions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('album_id', sa.Integer(), nullable=False),
        sa.Column('reaction_type', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['album_id'], ['photo_albums.id'], name=op.f('fk_photo_album_reactions_album_id_photo_albums'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_photo_album_reactions_user_id_users'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_photo_album_reactions'))
        )
    
    if 'photo_album_comment_reactions' not in tables:
        op.create_table('photo_album_comment_reactions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('comment_id', sa.Integer(), nullable=False),
        sa.Column('reaction_type', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['comment_id'], ['photo_album_comments.id'], name=op.f('fk_photo_album_comment_reactions_comment_id_photo_album_comments'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_photo_album_comment_reactions_user_id_users'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_photo_album_comment_reactions'))
        )

    # Helper function to drop constraint if it exists
    def drop_constraint_safe(table_name, constraint_name, batch_op, columns=None):
        fks = inspector.get_foreign_keys(table_name)
        # 1. Try by provided name first
        for fk in fks:
            if fk['name'] == constraint_name:
                print(f"Dropping constraint {constraint_name} on table {table_name} by name")
                batch_op.drop_constraint(constraint_name, type_='foreignkey')
                return True
        # 2. Try by columns if name didn't match or was None
        if columns:
            for fk in fks:
                if set(fk['constrained_columns']) == set(columns):
                    actual_name = fk['name']
                    if actual_name:
                        print(f"Dropping constraint {actual_name} on table {table_name} by columns {columns}")
                        batch_op.drop_constraint(actual_name, type_='foreignkey')
                        return True
                    else:
                        print(f"Found matching constraint on table {table_name} by columns {columns} but it has no name (SQLite?)")
                        # In SQLite batch mode, if we are redefining the table, 
                        # we don't necessarily need to call drop_constraint if it has no name,
                        # because we will redefine the columns and FKs in the new table anyway.
                        # But to be safe, we can try to drop by columns if Alembic supports it.
                        pass
        print(f"Constraint {constraint_name} not found on table {table_name} (tried name and columns)")
        return False

    with op.batch_alter_table('admin_permissions', schema=None) as batch_op:
        drop_constraint_safe('admin_permissions', 'admin_permissions_admin_id_fkey', batch_op, ['admin_id'])
        batch_op.create_foreign_key(batch_op.f('fk_admin_permissions_admin_id_users'), 'users', ['admin_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        drop_constraint_safe('chat_messages', 'chat_messages_receiver_id_fkey', batch_op, ['receiver_id'])
        drop_constraint_safe('chat_messages', 'chat_messages_sender_id_fkey', batch_op, ['sender_id'])
        batch_op.create_foreign_key(batch_op.f('fk_chat_messages_receiver_id_users'), 'users', ['receiver_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_chat_messages_sender_id_users'), 'users', ['sender_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('friendships', schema=None) as batch_op:
        drop_constraint_safe('friendships', 'friendships_user_id_fkey', batch_op, ['user_id'])
        drop_constraint_safe('friendships', 'friendships_friend_id_fkey', batch_op, ['friend_id'])
        batch_op.create_foreign_key(batch_op.f('fk_friendships_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_friendships_friend_id_users'), 'users', ['friend_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('photo_albums', schema=None) as batch_op:
        drop_constraint_safe('photo_albums', 'photo_albums_user_id_fkey', batch_op, ['user_id'])
        batch_op.create_foreign_key(batch_op.f('fk_photo_albums_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        drop_constraint_safe('reviews', 'reviews_product_id_fkey', batch_op, ['product_id'])
        drop_constraint_safe('reviews', 'reviews_user_id_fkey', batch_op, ['user_id'])
        batch_op.create_foreign_key(batch_op.f('fk_reviews_product_id_products'), 'products', ['product_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_reviews_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_photo_comments', schema=None) as batch_op:
        drop_constraint_safe('user_photo_comments', 'user_photo_comments_user_id_fkey', batch_op, ['user_id'])
        drop_constraint_safe('user_photo_comments', 'user_photo_comments_photo_id_fkey', batch_op, ['photo_id'])
        batch_op.create_foreign_key(batch_op.f('fk_user_photo_comments_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_user_photo_comments_photo_id_user_photos'), 'user_photos', ['photo_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_photo_reactions', schema=None) as batch_op:
        drop_constraint_safe('user_photo_reactions', 'user_photo_reactions_photo_id_fkey', batch_op, ['photo_id'])
        drop_constraint_safe('user_photo_reactions', 'user_photo_reactions_user_id_fkey', batch_op, ['user_id'])
        batch_op.create_foreign_key(batch_op.f('fk_user_photo_reactions_photo_id_user_photos'), 'user_photos', ['photo_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_user_photo_reactions_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_photos', schema=None) as batch_op:
        drop_constraint_safe('user_photos', 'user_photos_album_id_fkey', batch_op, ['album_id'])
        drop_constraint_safe('user_photos', 'user_photos_user_id_fkey', batch_op, ['user_id'])
        batch_op.create_foreign_key(batch_op.f('fk_user_photos_album_id_photo_albums'), 'photo_albums', ['album_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_user_photos_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_photos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_photos_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_user_photos_album_id_photo_albums'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'photo_albums', ['album_id'], ['id'])

    with op.batch_alter_table('user_photo_reactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_photo_reactions_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_user_photo_reactions_photo_id_user_photos'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_photos', ['photo_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('user_photo_comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_photo_comments_photo_id_user_photos'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_user_photo_comments_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'user_photos', ['photo_id'], ['id'])

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reviews_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_reviews_product_id_products'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('photo_albums', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_photo_albums_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])


    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_friendships_friend_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_friendships_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['friend_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_chat_messages_sender_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_chat_messages_receiver_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['receiver_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['sender_id'], ['id'])

    with op.batch_alter_table('admin_permissions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_admin_permissions_admin_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['admin_id'], ['id'])

    op.drop_table('photo_album_comment_reactions')
    op.drop_table('photo_album_reactions')
    op.drop_table('photo_album_comments')
    # ### end Alembic commands ###
