"""fix_file_upload_session_is_completed_type

Revision ID: 36c0def3c4c2
Revises: 2c4b6808b6a0
Create Date: 2026-02-14 08:01:25.628884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36c0def3c4c2'
down_revision: Union[str, Sequence[str], None] = '2c4b6808b6a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE file_upload_sessions ALTER COLUMN is_completed TYPE BOOLEAN USING is_completed::boolean")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_upload_sessions', 'is_completed',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
