"""Add deletion flags to ChatMessage

Revision ID: 7dac946c0e0b
Revises: 21d217c87b44
Create Date: 2026-02-14 12:02:08.883779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dac946c0e0b'
down_revision: Union[str, Sequence[str], None] = '21d217c87b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('deleted_by_sender', sa.Boolean(), nullable=True))
    op.add_column('chat_messages', sa.Column('deleted_by_receiver', sa.Boolean(), nullable=True))
    op.execute("UPDATE chat_messages SET deleted_by_sender = FALSE, deleted_by_receiver = FALSE")
    op.alter_column('chat_messages', 'deleted_by_sender', nullable=False)
    op.alter_column('chat_messages', 'deleted_by_receiver', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'deleted_by_receiver')
    op.drop_column('chat_messages', 'deleted_by_sender')
    # ### end Alembic commands ###
