"""review_1

Revision ID: 99591e81e1e8
Revises: cc15fb3c7261
Create Date: 2026-01-29 12:37:56.928717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99591e81e1e8'
down_revision: Union[str, Sequence[str], None] = 'cc15fb3c7261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'rating',
               existing_type=sa.NUMERIC(precision=1, scale=5),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'rating',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=1, scale=5),
               existing_nullable=True)
    # ### end Alembic commands ###
