"""add_duration_to_chat_messages

Revision ID: af99037b0ab3
Revises: 19b5f06206ac
Create Date: 2026-03-01 20:33:51.502083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af99037b0ab3'
down_revision: Union[str, Sequence[str], None] = '19b5f06206ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Получаем информацию о колонках
    conn = op.get_bind()
    from sqlalchemy import inspect
    inspector = inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('chat_messages')]
    
    if 'duration' not in columns:
        with op.batch_alter_table('chat_messages', schema=None) as batch_op:
            batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))
    else:
        print("Column 'duration' already exists in 'chat_messages', skipping...")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
