"""add thumbnail to product

Revision ID: b3925f2783ac
Revises: 083de28a731c
Create Date: 2026-02-12 16:59:19.842444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3925f2783ac'
down_revision: Union[str, Sequence[str], None] = '083de28a731c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('thumbnail_url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'thumbnail_url')
    # ### end Alembic commands ###
