"""add_reply_to_id_to_chat_messages

Revision ID: b76e1a9c3d4e
Revises: a1b2c3d4e5f6
Create Date: 2026-03-06 14:55:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b76e1a9c3d4e'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [c['name'] for c in inspector.get_columns('chat_messages')]
    
    if 'reply_to_id' not in columns:
        with op.batch_alter_table('chat_messages', schema=None) as batch_op:
            batch_op.add_column(sa.Column('reply_to_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key('fk_chat_messages_reply_to_id', 'chat_messages', ['reply_to_id'], ['id'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chat_messages_reply_to_id', type_='foreignkey')
        batch_op.drop_column('reply_to_id')
    # ### end Alembic commands ###
