"""add_forwarded_from_to_chat_messages

Revision ID: c2d3e4f5a6b7
Revises: 0c1d2e3f4a5b
Create Date: 2026-09-26 12:00:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c2d3e4f5a6b7'
down_revision: Union[str, Sequence[str], None] = '0c1d2e3f4a5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [c['name'] for c in inspector.get_columns('chat_messages')]

    if 'forwarded_from_id' not in columns:
        with op.batch_alter_table('chat_messages', schema=None) as batch_op:
            batch_op.add_column(sa.Column('forwarded_from_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key('fk_chat_messages_forwarded_from_id', 'users', ['forwarded_from_id'], ['id'])

    if 'forwarded_from_name' not in columns:
        with op.batch_alter_table('chat_messages', schema=None) as batch_op:
            batch_op.add_column(sa.Column('forwarded_from_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chat_messages_forwarded_from_id', type_='foreignkey')
        batch_op.drop_column('forwarded_from_id')
        batch_op.drop_column('forwarded_from_name')
    # ### end Alembic commands ###
