"""add media support to chat

Revision ID: e2acba639b62
Revises: f8c5ab23aa93
Create Date: 2026-02-12 16:45:12.575982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2acba639b62'
down_revision: Union[str, Sequence[str], None] = 'f8c5ab23aa93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('file_path', sa.String(), nullable=True))
    op.add_column('chat_messages', sa.Column('message_type', sa.String(), nullable=True))
    # Заполняем существующие записи значением по умолчанию
    op.execute("UPDATE chat_messages SET message_type = 'text' WHERE message_type IS NULL")
    # Делаем колонку nullable=False
    op.alter_column('chat_messages', 'message_type', nullable=False)
    
    op.alter_column('chat_messages', 'message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('chat_messages', 'message_type')
    op.drop_column('chat_messages', 'file_path')
    # ### end Alembic commands ###
