"""google_auth

Revision ID: f33c2f49979b
Revises: bb8f6151e317
Create Date: 2026-02-28 20:20:13.029592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f33c2f49979b'
down_revision: Union[str, Sequence[str], None] = 'bb8f6151e317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    is_postgres = bind.dialect.name == 'postgresql'
    inspector = sa.inspect(bind)

    # В Postgres колонка tsv уже создается в начальной миграции.
    # Для других БД (SQLite) добавляем её, если она еще не создана.
    if not is_postgres:
        columns_products = [c['name'] for c in inspector.get_columns('products')]
        if 'tsv' not in columns_products:
            op.add_column('products', sa.Column('tsv', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    is_postgres = bind.dialect.name == 'postgresql'

    if not is_postgres:
        op.drop_column('products', 'tsv')
    # ### end Alembic commands ###
