"""google_auth

Revision ID: f33c2f49979b
Revises: bb8f6151e317
Create Date: 2026-02-28 20:20:13.029592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f33c2f49979b'
down_revision: Union[str, Sequence[str], None] = 'bb8f6151e317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('tsv', sa.String(), nullable=True))
    op.drop_constraint(None, 'user_photo_reactions', type_='foreignkey')
    op.drop_constraint(None, 'user_photo_reactions', type_='foreignkey')
    op.create_foreign_key(None, 'user_photo_reactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_photo_reactions', 'user_photos', ['photo_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_photo_reactions', type_='foreignkey')
    op.drop_constraint(None, 'user_photo_reactions', type_='foreignkey')
    op.create_foreign_key(None, 'user_photo_reactions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_photo_reactions', 'user_photos', ['photo_id'], ['id'])
    op.drop_column('products', 'tsv')
    # ### end Alembic commands ###
