"""add_group_chats

Revision ID: f5a6b7c8d9e0
Revises: e4f5a6b7c8d9
Create Date: 2026-09-26 19:35:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f5a6b7c8d9e0'
down_revision: Union[str, Sequence[str], None] = 'e4f5a6b7c8d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    if 'group_chats' not in existing_tables:
        op.create_table(
            'group_chats',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(), nullable=False),
            sa.Column('avatar_url', sa.String(), nullable=True),
            sa.Column('owner_id', sa.Integer(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id'),
        )

    existing_tables = inspector.get_table_names()
    if 'group_chat_members' not in existing_tables:
        op.create_table(
            'group_chat_members',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('group_id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('role', sa.String(), nullable=True),
            sa.Column('joined_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['group_id'], ['group_chats.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('group_id', 'user_id', name='uq_group_chat_member_group_user'),
        )

    # Добавляем group_id к chat_messages, receiver_id делаем nullable (для групповых сообщений)
    existing_columns = [c['name'] for c in inspector.get_columns('chat_messages')]
    if 'group_id' not in existing_columns:
        with op.batch_alter_table('chat_messages') as batch_op:
            batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key(
                'fk_chat_messages_group_id', 'group_chats', ['group_id'], ['id'], ondelete='CASCADE'
            )
            batch_op.alter_column('receiver_id', existing_type=sa.Integer(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages') as batch_op:
        batch_op.drop_constraint('fk_chat_messages_group_id', type_='foreignkey')
        batch_op.drop_column('group_id')
    op.drop_table('group_chat_members')
    op.drop_table('group_chats')
    # ### end Alembic commands ###
