import { StyleSheet, Platform } from 'react-native';
import { getShadow } from '../../utils/shadowStyles';

export const styles = StyleSheet.create({
  container: { 
    flex: 1, 
    ...Platform.select({
      web: {
        height: '100vh',
        maxHeight: '100vh',
        overflow: 'hidden'
      }
    })
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    borderBottomWidth: 1,
    flexShrink: 0,
    ...getShadow('#000', { width: 0, height: 1 }, 0.1, 1, 2),
  },
  headerInfoContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerIconButton: {
    padding: 8,
    borderRadius: 20,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 2,
    flex: 1,
  },
  searchInput: {
    flex: 1,
    height: 36,
    borderRadius: 18,
    paddingHorizontal: 12,
    fontSize: 14,
  },
  searchControls: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  searchNav: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.05)',
    borderRadius: 15,
    marginLeft: 4,
    paddingLeft: 4,
  },
  searchCount: {
    fontSize: 10,
    fontWeight: '600',
    minWidth: 24,
    textAlign: 'center',
  },
  searchNavItem: {
    padding: 0,
  },
  noResultsText: {
    fontSize: 10,
    marginHorizontal: 4,
    fontStyle: 'italic',
  },
  searchClose: {
    padding: 4,
    marginLeft: 2,
  },
  scrollDownButton: {
    position: 'absolute',
    bottom: 80,
    right: 20,
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    zIndex: 10,
  },
  backButton: {
    marginRight: 10,
    padding: 5,
  },
  headerInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  headerAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    marginRight: 10,
  },
  headerAvatarContainer: {
    position: 'relative',
  },
  headerOnlineBadge: {
    position: 'absolute',
    right: 8,
    bottom: 0,
    width: 10,
    height: 10,
    borderRadius: 5,
    borderWidth: 1.5,
    zIndex: 1
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  headerStatus: {
    fontSize: 12,
  },
  offlineBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 4,
    paddingHorizontal: 10,
  },
  offlineText: {
    fontSize: 12,
    marginLeft: 6,
    fontWeight: '500',
  },
  messageWrapper: {
    flexDirection: 'row',
    marginVertical: 3,
    paddingHorizontal: 10,
    alignItems: 'flex-end',
  },
  receivedWrapper: {
    justifyContent: 'flex-start',
  },
  sentWrapper: {
    justifyContent: 'flex-end',
  },
  mediaGridContainer: {
    width: 260,
    marginTop: 2,
  },
  mediaGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  messageBubble: { 
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 18, 
    maxWidth: '85%',
    ...getShadow('#000', { width: 0, height: 1 }, 0.1, 2, 1),
  },
  sent: { 
    alignSelf: 'flex-end', 
    borderBottomRightRadius: 2, 
    elevation: 2 
  },
  received: { 
    alignSelf: 'flex-start', 
    borderBottomLeftRadius: 2, 
    elevation: 1 
  },
  messageText: { fontSize: 13, lineHeight: 18 },
  messageFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginTop: 1,
    alignSelf: 'flex-end',
  },
  messageTime: {
    fontSize: 9,
    marginRight: 4,
  },
  statusIcon: {
    marginLeft: 2,
  },
  inputContainer: { flexDirection: 'row', padding: 10, flexShrink: 0 },
  selectionHeader: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 40,
  },
  selectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginLeft: 15,
    flex: 1,
  },
  selectionIndicator: {
    position: 'absolute',
    top: 5,
    right: 5,
    zIndex: 1,
  },
  input: { 
    flex: 1, 
    borderWidth: 1, 
    borderRadius: 24, 
    paddingHorizontal: 16, 
    paddingTop: 8,
    paddingBottom: 8,
    minHeight: 40,
    maxHeight: 120,
    fontSize: 16 
  },
  sendButton: { justifyContent: 'center', marginLeft: 10 },
  sendButtonText: { color: '#007AFF', fontWeight: 'bold' },
  attachButton: { justifyContent: 'center', marginRight: 10, paddingHorizontal: 10 },
  attachButtonText: { fontSize: 24, color: '#007AFF' },
  recordingContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    height: 40,
  },
  recordingIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  recordingDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#ff3b30',
    marginRight: 8,
  },
  recordingTimeText: {
    fontSize: 16,
    fontWeight: '500',
  },
  recordingHint: {
    fontSize: 14,
    fontStyle: 'italic',
  },
  recordedContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 5,
    height: 40,
  },
  deleteRecordingButton: {
    padding: 5,
  },
  recordingWaveformPlaceholder: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.05)',
    borderRadius: 20,
    paddingHorizontal: 15,
    height: 36,
    marginHorizontal: 10,
  },
  uploadProgressContainer: { 
    padding: 10, 
    backgroundColor: '#fff', 
    borderBottomWidth: 1, 
    borderColor: '#eee' 
  },
  uploadProgressInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 5,
  },
  progressBarBackground: {
    height: 4,
    backgroundColor: '#eee',
    borderRadius: 2,
    overflow: 'hidden',
  },
  progressBar: { 
    height: '100%', 
  },
  fileLinkText: { color: '#fff', textDecorationLine: 'underline', marginBottom: 5 },
  fullScreenContainer: { flex: 1, backgroundColor: 'black' },
  fullScreenImage: { width: '100%', height: '100%' },
  fullScreenVideo: { width: '100%', height: '100%' },
  // Fullscreen media controls (custom)
  fullScreenControlsTop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    paddingTop: 40,
    paddingHorizontal: 16,
    paddingBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 20,
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  fullScreenIconButton: {
    padding: 6,
  },
  fullScreenControlsBottom: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 16,
    paddingBottom: 22,
    paddingTop: 20,
    zIndex: 20,
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  fullScreenCenterButtonContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  fullScreenCenterPlayButton: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fullScreenTimelineRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  fullScreenTimeText: {
    color: '#fff',
    fontSize: 12,
    width: 48,
    textAlign: 'center',
  },
  fullScreenSliderContainer: {
    flex: 1,
    height: 28,
    justifyContent: 'center',
    marginHorizontal: 10,
  },
  fullScreenSliderTrack: {
    height: 3,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,0.35)',
  },
  fullScreenSliderFill: {
    position: 'absolute',
    left: 0,
    height: 3,
    borderRadius: 2,
    backgroundColor: '#fff',
  },
  fullScreenSliderThumb: {
    position: 'absolute',
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#fff',
  },

  fsDownloadBadge: {
    position: 'absolute',
    bottom: 90,
    left: 20,
    right: 20,
    zIndex: 25,
    backgroundColor: 'rgba(0,0,0,0.75)',
    borderRadius: 10,
    paddingVertical: 6,
    paddingHorizontal: 12,
    alignItems: 'center',
  },
  fsDownloadBytesText: {
    color: '#4FC3F7',
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 5,
  },
  fsProgressBarTrack: {
    width: '100%',
    height: 4,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 2,
    overflow: 'hidden',
  },
  fsProgressBarFill: {
    height: 4,
    backgroundColor: '#4FC3F7',
    borderRadius: 2,
  },
  fsStallText: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 11,
    marginTop: 4,
  },

  // Legacy (kept for compatibility; not used by custom controls)
  closeButton: { position: 'absolute', top: 40, right: 20, zIndex: 10 },
  downloadButton: { position: 'absolute', top: 40, left: 20, zIndex: 10 },
  videoPreviewOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  videoPreviewContainer: {
    width: 250,
    height: 250,
    borderRadius: 125,
    overflow: 'hidden',
    borderWidth: 3,
    borderColor: '#fff',
    backgroundColor: '#000',
  },
  videoPreview: {
    width: '100%',
    height: '100%',
  },
  videoRecordingTimerContainer: {
    position: 'absolute',
    bottom: 20,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.6)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  videoRecordingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#ff3b30',
    marginRight: 6,
  },
  videoRecordingTimerText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
  },
  videoNoteModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.85)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  videoNoteModalContent: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoNoteModalCircle: {
    width: 320,
    height: 320,
    borderRadius: 160,
    overflow: 'hidden',
    backgroundColor: '#000',
    borderWidth: 0,
    borderColor: 'rgba(255,255,255,0.2)',
    ...getShadow('#000', { width: 0, height: 10 }, 0.5, 20, 15),
  },
  videoNoteSliderContainer: {
    width: 320,
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoNoteProgressBar: {
    width: 280,
    height: 4,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 2,
    marginTop: 20,
    overflow: 'hidden',
  },
  videoNoteProgressFill: {
    height: '100%',
    backgroundColor: '#fff',
    borderRadius: 2,
  },
  videoNoteControlsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 15,
    width: 280,
    justifyContent: 'space-between',
  },
  videoNoteTimeText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '500',
    width: 60,
    textAlign: 'center',
  },
  videoNotePlayPauseBtn: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'rgba(255,255,255,0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
  },
  videoNoteProgressRing: {
    position: 'absolute',
    top: -4,
    left: -4,
    right: -4,
    bottom: -4,
    borderRadius: 164,
    borderWidth: 4,
    borderColor: 'rgba(255,255,255,0.3)',
  },
  videoNoteModalVideo: {
    width: '100%',
    height: '100%',
  },
  videoNoteModalClose: {
    marginTop: 30,
    padding: 10,
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderRadius: 30,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
  },
  replyPreviewContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.05)',
    backgroundColor: 'transparent',
    width: '100%',
  },
  replyPreviewBorder: {
    width: 3,
    height: '100%',
    borderRadius: 2,
    marginRight: 10,
  },
  replyPreviewContent: {
    flex: 1,
    justifyContent: 'center',
  },
  replyPreviewSender: {
    fontSize: 13,
    fontWeight: 'bold',
  },
  replyPreviewText: {
    fontSize: 12,
  },
  replyPreviewClose: {
    padding: 5,
  },
  replyMessageContainer: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: 'rgba(0,0,0,0.05)',
    marginBottom: 4,
    borderLeftWidth: 3,
  },
  replyMessageSender: {
    fontSize: 12,
    fontWeight: 'bold',
  },
  replyMessageText: {
    fontSize: 11,
  },
  forwardedLabelContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  forwardedLabelText: {
    fontSize: 12,
    fontWeight: 'bold',
    marginLeft: 4,
  },
  forwardedCommentContainer: {
    marginTop: 6,
    paddingTop: 6,
    borderTopWidth: 1,
  },
  dateSeparatorWrapper: {
    alignItems: 'center',
    marginVertical: 10,
  },
  dateSeparatorBubble: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 12,
  },
  dateSeparatorText: {
    fontSize: 12,
    fontWeight: '600',
  },
  reactionBarWrapper: {
    flexDirection: 'row',
    alignSelf: 'center',
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 24,
    borderWidth: 1,
    marginBottom: 6,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
  },
  reactionBarEmojiButton: {
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  reactionBarEmojiText: {
    fontSize: 24,
  },
  reactionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 4,
  },
  reactionBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 10,
    marginRight: 4,
    marginTop: 2,
  },
  reactionBadgeEmoji: {
    fontSize: 13,
  },
  reactionBadgeCount: {
    fontSize: 11,
    fontWeight: '600',
    marginLeft: 3,
  },
});

export default styles;
